### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jldlxs** [capawesome-team/capacitor-android-foreground-service#6] opened 2023-05-27 01:01 UTC
**Plugin version:**
5.0.0

**Platform(s):**
Android

**Current behavior:**
I don't know if it is a bug or if it is the intended behavior.
When requestManageOverlayPermission(), the app opens the settings screen with ALL installed apps listed, instead of prompting the user to ALLOW ou DENY.
This behavior is not good for me because my app relies on moveToForeground() to work, and the way it is, is not natural for user to find my app in the middle of all installed apps and enter the configs to allow.

**Expected behavior:**
Prompt user to allow/deny permission, instead of open settings.

**Steps to reproduce:**
Just calling requestManageOverlayPermission()

**Related code:**
allowPermission(){
         requestManageOverlayPermission()
}

Thanks a lot.

**Comment by robingenz** [comment] 2023-05-27 16:44
This is the intended behavior. I can request the permission, but I can't tell Android how to request the permission. I am sorry that I do not have better news.

For this reason, I am closing this issue.

**Closed** 2023-05-27 16:44 UTC
Labels: wontfix, platform: android
