### ISSUE TITLE
bug: Unexpected behaviour.

### ISSUE THREAD

**Issue by cokeeffekt** [capawesome-team/capacitor-android-foreground-service#5] opened 2023-03-05 00:10 UTC
**Plugin version:**

"@capawesome-team/capacitor-android-foreground-service": "^0.1.0",

**Platform(s):**

Android

**Current behavior:**

1. ForegroundService.startForegroundService does not trigger the notification.
2 . The the app still goes unresponsive after a few minutes as if its not running in foreground.

**Expected behavior:**

1. Expecting a notification once the ForegroundService.startForegroundService function is run matching information provided title/body. I also expect Foreground Services to not become unresponsive.
2. I expect the app in foreground to run until its told to stop.

**Steps to reproduce:**

I have a blank capacitor project with minimal plugins,  running the startForegroundService function shows the android "App is running" message in the notification pull down, but no notification matching the title/body of the options supplied.

![image](https://user-images.githubusercontent.com/4961122/222934553-0f29364e-932e-4602-8dd9-42d614fa32c9.png)
example of the message i see when forground running, it doesnt match the information provided.

The Foreground Service app eventualy becomes lost to doze, app cant do anything in the service until the app is refocused.

My app needs to control a bluetooth device while in forground for extended period of time. after ~5 minutes of app running in foreground (app minimized) pushNotificationReceived and bluetooth communication events stop running.

**Related code:**

```
import { ForegroundService } from '@capawesome-team/capacitor-android-foreground-service';

window.startForegroundService = async () => {
  await ForegroundService.startForegroundService({
    body: 'Where is this?',
    id: 12398473,
    title: 'Missing',
    smallIcon: 'ic_launcher_round',
  });
};

window.stopForegroundService = async () => {
  await ForegroundService.stopForegroundService();
};
```

**Other information:**

Test Devices tested
Samsung S10+ android 12
LG g7 android 10

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/android: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/cli: 4.7.0

[success] Android looking great! 👌
```

**Comment by cokeeffekt** [comment] 2023-03-05 00:36
Side note, i have since added your BatteryOptimization plugin, to see if requestIgnoreBatteryOptimization would prevent forground services from going unresponsive still not working at expected.

**Comment by cokeeffekt** [comment] 2023-03-07 22:56
So after more exploration on this issue, i feel like this might be prematurely closed.  @robingenz 

> Unfortunately, this is completely dependent on the manufacturer. On my Google Pixel, for example, the notification is displayed with title and message. Samsung seems to do this differently with Foreground Notifications.

Trying on a Pixel XL i get the wrong notifcation when using latest capacitor platforms. But your demo app works fine on all my devices so i rolled back my capacitor versions 

```
  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0
```

And notifications work as expected on all my devices. So the notification issue is code related not platform dependant

As for the app going idle, i think that might be platform dependant... still looking into why `pushNotificationReceived` messages go ignored, that one seems to only be on my Samsung devices.

Hoping this issue can get reopened as i think its clearly not normal behaviour, especially seeing that it seems to be related to cap version or cap platform version . Thanks @robingenz for taking the initial look.

**Comment by robingenz** [comment] 2023-03-07 23:12
@cokeeffekt In that case, I will definitely look at the issue again.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by robingenz** [comment] 2023-10-21 14:27
I close this issue because no reproduction was provided.

**Closed by robingenz** 2023-10-21 14:27 UTC
Labels: platform: android, needs: reproduction, needs: reply
